---

- name: "sudoers : create sudo file"
  copy:
    dest: "/etc/sudoers.d/10-{{ item.name }}"
    content: |
      {{ item.name }}   ALL=(ALL) ALL
    validate: "/usr/sbin/visudo -cf %s"
    mode: "0644"
  when:
    - ( item.sudo_nopasswd is not defined ) or ( not item.sudo_nopasswd )
    - item.use_sudo

- name: "sudoers : create sudo file nopasswd"
  copy:
    dest: "/etc/sudoers.d/10-{{ item.name }}"
    content: |
      {{ item.name }}   ALL=(ALL) NOPASSWD:ALL
    validate: "/usr/sbin/visudo -cf %s"
    mode: "0644"
  when:
    - item.sudo_nopasswd is defined
    - item.sudo_nopasswd
    - item.use_sudo

- name: "sudoers : delete sudo file"
  file:
    path: "/etc/sudoers.d/10-{{ item.name }}"
    state: absent
  when: not item.use_sudo
